# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ProjectTemplate' do
  # React package stuff

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # React related stuff
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'Bolts'

  # Other packages
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Analytics', '~> 6.3.0'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'


  # pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
  # pod 'FBSDKCoreKit', '~> 4.38.0'
  # pod 'FBSDKLoginKit', '~> 4.38.0'
  # pod 'FBSDKShareKit', '~> 4.38.0'
  # pod 'RSKImageCropper'
  # pod 'QBImagePickerController'
  # pod 'Firebase/Core', '4.2.0'
  # pod 'FirebaseMessaging'
  # pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
  # pod 'react-native-camera', path: '../node_modules/react-native-camera'
  # pod 'CodePush', :path => '../node_modules/react-native-code-push'
  # pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  # pod 'RNShare', :path => '../node_modules/react-native-share'
  # pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'react-native-blur', :path => '../node_modules/react-native-blur'
  # pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  use_native_modules!

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
